#Makefile for qti nfc drivers

NFC_ROOT ?= $(src)

include $(srctree)/$(NFC_ROOT)/config/gki_nfc.conf

LINUXINCLUDE    += -I$(srctree)/$(NFC_ROOT)/include/uapi/linux/nfc

LINUXINCLUDE   += -include $(srctree)/$(NFC_ROOT)/config/gki_nfc_conf.h

LINUXINCLUDE   += -I$(srctree)/techpack/securemsm-kernel/smcinvoke/
LINUXINCLUDE   += -I$(srctree)/techpack/securemsm-kernel/linux/
LINUXINCLUDE   += -I$(srctree)/techpack/securemsm-kernel/include/linux/

obj-$(CONFIG_NXP_NFC_I2C) += nxp-nci.o

#source files
nxp-nci-objs += nfc/ese_cold_reset.o \
                nfc/common.o \
		nfc/common_nxp.o \
		nfc/common_qcom.o \
		nfc/i2c_drv.o
