# SPDX-License-Identifier: GPL-2.0-only

MSM_HW_FENCE_ROOT ?= $(src)

KDIR := $(TOP)/kernel_platform/msm-kernel
include $(MSM_HW_FENCE_ROOT)/../config/kalamammdrivers.conf
LINUXINCLUDE += -include $(srctree)/$(MSM_HW_FENCE_ROOT)/../config/kalamammdriversconf.h \
		-I$(srctree)/$(MSM_HW_FENCE_ROOT)/include/ \
		-I$(srctree)/techpack/synx-kernel/msm/synx/ \
		-I$(srctree)/techpack/synx-kernel/include/uapi/synx/media/

ifdef CONFIG_QTI_HW_FENCE
obj-m += msm_hw_fence.o

msm_hw_fence-y := src/msm_hw_fence.o \
		src/hw_fence_drv_priv.o \
		src/hw_fence_drv_utils.o \
		src/hw_fence_drv_debug.o \
		src/hw_fence_drv_ipc.o

ifneq ($(CONFIG_ARCH_KALAMA), y)
msm_hw_fence-y += src/msm_hw_fence_synx_translation.o
endif

msm_hw_fence-$(CONFIG_DEBUG_FS) += src/hw_fence_ioctl.o

endif
EXTRA_CFLAGS += -Wformat-extra-args -Wstrict-prototypes -Wformat-insufficient-args \
		-Wformat-invalid-specifier -Wformat-zero-length -Wnonnull
